Add a script for forced payment refund (#45)
* Add script for batch refund processing

diff --git a/scripts/lib/logging b/scripts/lib/logging
--- a/scripts/lib/logging
+++ b/scripts/lib/logging
@@ -4,14 +4,18 @@ BY="\x1b[1;33m"
 RS="\x1b[0m"
 
 function err {
-  echo -e "${BR}[ERROR]${RS}" "${1}"
-  exit "${2:-127}"
+  echo -e "${BR}[ERROR]${RS}" "${*}"
+  exit 127
 }
 
 function warn {
-  echo -e "${BY}[WARNING]${RS}" "${1}"
+  echo -e "${BY}[WARNING]${RS}" "${*}"
+}
+
+function info {
+  echo -e "${BW}[INFO]${RS}" "${*}"
 }
 
 function em {
-  echo "${BW}${1}${RS}"
+  echo "${BW}${*}${RS}"
 }
